# Book settings
title: Twisted bilayer WSe2
author: Hidde Dijkstra

latex:
  latex_documents:
    targetname: book.tex
    
sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    

    
