# Book settings
title: hidde-dijkstra.github.io
author: Hidde Dijkstra
logo: logo.svg

latex:
  latex_documents:
    targetname: book.tex
    
sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js

bibtex_bibfiles:
    - master-thesis/references.bib 
